auth/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import auth.views
import courses.views

urlpatterns = [
    url(r'login/', auth.views.logIn2, name="login"),
    url(r'logout/', auth.views.user_logout, name='logout'),
    url(r'register/', auth.views.register2, name="register"),
    url(r'user/(?P<userhash>-?\d+)', auth.views.confirmUser, name='confirm'),
    url(r'user/company$', auth.views.proposal_to_be_company, name='proposal_to_be_company'),
    url(r'user/profile$', auth.views.profile, name='profile'),
    url(r'user/profile/edit$', auth.views.profileEdit, name='edit'),
    url(r'user/proposal$', auth.views.proposal, name='proposal'),  # post_request
    url(r'user/proposal/(?P<hash>-?\d+)$', auth.views.confirmCompany, name='confirm_company'),
    url(r'user/proposal/(?P<hash>-?\d+)/delete$', auth.views.deleteCompany, name='delete_company'),
    url(r'user/unsubscribe$', auth.views.un_subscribe, name='un_teach'),
    url(r'certificates$',auth.views.show_certificates,name='certificates'),
]

courses/urls.py
from django.conf.urls import include, url
from courses import views

# Ставьте норм урлы, чо как в деревне

urlpatterns = [
    url(r'^courses/all$', views.list_courses, name='all'),
    url(r'^courses/search', views.course_search, name="search"),
    url(r'^courses/(?P<course_id>\d+)$', views.show_course, name='one'),
    url(r'^courses/(?P<course_id>\d+)/lections$', views.list_lections, name='lections'),
    url(r'^courses/(?P<course_id>\d+)/lections/(?P<lection_id>\d+)$', views.show_lection, name='lection'),
    url(r'^courses/(?P<course_id>\d+)/lections/(?P<lection_id>\d+)/tasks$', views.show_tasks, name='lection_task'),
    url(r'^courses/(?P<course_id>\d+)/reviews$', views.reviews, name='reviews'),
    url(r'^courses/(?P<course_id>\d+)/test$', views.show_test, name='test'),
    url(r'^courses/(?P<course_id>\d+)/support', views.support, name='support'),
    #url(r'^courses/(?P<course_id>\d+)/')
    url(r'^$', views.main, name='main')
]

project/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from auth import views
import auth.views
from courses import views
from project import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^auth/', include('auth.urls', namespace='auth')),
    url(r'^', include('courses.urls', namespace='courses'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/views.py
import json
import random
from _operator import attrgetter
from itertools import chain
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.mail import send_mail
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import Http404
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http.response import HttpResponseRedirect as Redirect, HttpResponseRedirect, HttpResponseForbidden, \
    HttpResponse, JsonResponse
from django.template import RequestContext
from django.template.context_processors import csrf
from django.urls import reverse_lazy
from django.utils import dateformat
from auth.validators.decorator import login_required_24hours
from courses.forms import ReviewForm, SupportForm, UploadFileForm
from courses.models import *
from courses.validators.decorator import *
from courses.validators.validator import user_must_subscribe


def main(request):
    args = {}
    # args['favorite_courses'] = FavoriteCourses.objects.all()[:3]
    args['reviews'] = Review.objects.filter(course=None)
    args['selected_courses'] = FavoriteCourses.objects.all()
    return render(request, 'main.html', args)


def list_courses(request):
    args = {'courses': Course.objects.all()}
    pagination = Paginator(args['courses'], 6)
    page = request.GET.get('page')
    args['directions'] = directions_of_training
    try:
        courses = pagination.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        courses = pagination.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        courses = pagination.page(pagination.num_pages)
    args['courses'] = courses
    return render(request, 'courses/list_courses.html', args)


def show_course(request, course_id):
    if request.method == 'POST':
        if not request.user.is_authenticated():
            return HttpResponseRedirect('/auth/login/?next=/courses/%s' % course_id)

        if request.POST['form'] == 'subscribe':
            if not Subscribe.objects.filter(student=request.user.student_user, course_id=course_id).exists():
                if Lection.objects.filter(course_id=course_id).exists():
                    lection = Lection.objects.filter(course=course_id)
                    course = get_object_or_404(Course, pk=course_id)
                    if course.date_begining.timestamp() < datetime.datetime.now().timestamp() and course.date_ending.timestamp() > datetime.datetime.now().timestamp():
                        Subscribe(student=request.user.student_user, course_id=course_id,
                                  lection_status=lection.get(order=1)).save()
                    else:
                        raise Http404(
                            'Невозможно записаться на курс, так как вы не успели записаться до даты окончания записи.')
                else:
                    raise Http404("У курса нет лекций")
            else:
                Subscribe.objects.filter(student=request.user.student_user, course_id=course_id).delete()
            return HttpResponseRedirect(reverse('courses:one', kwargs={'course_id': course_id}))
    else:
        show_final_test = False
        has_previous = hasattr(Course.objects.get(id=course_id), 'course_next')
        certificate = False
        button = True
        if not request.user.is_authenticated and has_previous:
            button = False
        subscribe_exists = False
        not_80_percent = True
        if request.user.is_authenticated():
            student = request.user.student_user
            if Subscribe.objects.filter(student=student, course_id=course_id).exists():
                subscribe = Subscribe.objects.get(course_id=course_id, student=student)
                course = get_object_or_404(Course, id=course_id)
                not_80_percent = False if course.control_points * 0.8 <= subscribe.points else True
                if Subscribe.objects.get(student=student,
                                         course_id=course_id).final_test_points >= Course.objects.get(
                    id=course_id).control_final_test_points:
                    certificate = True
                if Subscribe.objects.get(student=student, course_id=course_id).points >= Course.objects.get(
                        id=course_id).control_points:
                    show_final_test = True
            if has_previous:
                course = Course.objects.get(id=course_id).course_next
                if Subscribe.objects.filter(student=student, course=course).exists():
                    if Subscribe.objects.get(student=student,
                                             course=course).final_test_points < course.control_final_test_points:
                        button = False
                else:
                    button = False
            subscribe_exists = Subscribe.objects.filter(student=student, course_id=course_id).exists()

        course = get_object_or_404(Course, id=course_id)

        lection = None
        try:
            lection = Lection.objects.filter(course_id=course.id).exclude(is_final=True).order_by('order')
        except Exception:
            raise Http404('Course doesn\'t have lections')

        review = show_review(request, course_id)

        return render(request, 'courses/show_course.html', {'course': course,
                                                            'subscribed': subscribe_exists,
                                                            'lections': lection,
                                                            'reviews': review['reviews'],
                                                            'errors': review['errors'],
                                                            'count': len(review['reviews']),
                                                            'button': button,
                                                            'certificate': certificate,
                                                            "not_80_percent": not_80_percent,
                                                            'show_test': show_final_test
                                                            })


@login_required_24hours(login_url=reverse_lazy('auth:logout'))
@not_subscribed_fuckoff(user_must_subscribe)
def list_lections(request, course_id):
    args = {}
    if request.method == 'GET':
        course = get_object_or_404(Course, id=course_id)
        lections = Lection.objects.filter(course=course).exclude(is_final=True).order_by('order')
        args['course'] = course
        args['lections'] = lections
        return render(request, 'courses/list_lections.html', args)
    else:
        pass


@login_required_24hours(login_url=reverse_lazy('auth:logout'))
@not_subscribed_fuckoff(user_must_subscribe)
def show_lection(request, course_id, lection_id):
    args = {}
    if request.method == "GET":
        student_exists = Student.objects.filter(user=request.user.id).exists()
        if not student_exists:
            raise Http404('Вход доступен только студентам!')
        else:
            tasks = Tasks.objects.filter(lection_id=lection_id)
            student = Student.objects.get(user=request.user.id)
            course = get_object_or_404(Course, pk=course_id)
            args['course'] = course
            lections = None
            comments = None
            replyes = None
            try:
                lection = Lection.objects.filter(course_id=course_id).get(id=lection_id)
                comments = Comments.objects.filter(lection_id=lection_id).order_by('-pub_date')
                replyes = RepsComment.objects.filter(lection_id=lection_id)
            except:
                raise Http404("This resource is not available.")
            args['tasks'] = tasks
            args['lection'] = lection
            args['comments'] = comments
            args['replyes'] = replyes
            args['objects'] = sorted(chain(comments, replyes), key=attrgetter('pub_date'), reverse=True)
            # Check for subscribed user to access in lection
            # if not Subscribe.objects.filter(course=course).filter(student=student).filter(
            #         lection_status__order__gte=lection_id).exists():
            #     raise Http404("Access denied!")
            # else:
            return render(request, 'courses/show_lection.html', args)
    elif request.method == 'POST':
        args.update(csrf(request))
        if (request.POST.get('superuser') == 'aaa'):
            if len(request.POST['comment_message']) > 0:
                comment = Comments()
                comment.message = request.POST['comment_message']
                comment.student = request.user.student_user
                comment.lection = get_object_or_404(Lection, pk=int(lection_id))
                comment.save()
                data = {
                    'comment_user_photo': comment.student.photo.url,
                    'comment_username': comment.student.user.first_name + ' ' + comment.student.user.first_name,
                    'comments_pub_date': dateformat.format(comment.pub_date, settings.DATE_FORMAT),
                    'comment_like': comment.like,
                    'comment_messaage': comment.message
                }
                return JsonResponse(data)
            else:
                return JsonResponse({'error': "Нельзя оставлять пустой комментарий"})
        else:
            try:
                reply = RepsComment()
                message_rep = request.POST['comment_message']
                message_rep = "<p><b>" + message_rep
                message_rep_massive = message_rep.split(':')
                message_rep_massive[1] = "</b></p>" + message_rep_massive[1]
                message_rep = ""
                for mess in message_rep_massive:
                    message_rep += mess

courses/templates/courses/list_courses.html
{% extends "base.html" %}
{% load static %}
{% load cloudinary %}
{% block main %}
    <link rel="stylesheet" href="{% static "css/list_courses.css" %}">

    {#    <script src="{% static 'js/matchHeight.js' %}"></script>#}
    {#    <script>#}
    {##}
    {#        $(function () {#}
    {#            $('.course-item').matchHeight();#}
    {#        });#}
    {#    </script>#}
    <div class="main-part">
        <div class="container" role="main">
            <div class="page-header" style="border-bottom: none">
                <h2 class="text-center"><strong>Доступные курсы</strong></h2>
            </div>

            <div class="row" style="margin:auto;">
                <div class="col-sm-12">
                    <div id="imaginary_container">

                        <div class="panel panel-default">
                            <div class="panel-body" style="text-align: center">

                                <form class="form-inline" method="get" action="{% url 'courses:search' %}">
                                    <div class="form-group">
                                        <label for="searchtext">Название:</label>
                                        <input type="text" id="searchtext" name="search_text"
                                               class="form-control input-sm"
                                               placeholder="Введение в Python" style="margin-right: 0">
                                    </div>
                                    <div class="form-group ">
                                        <label class="" for="searchselect">Направление:</label>

                                        <select class="form-control input-sm" id="searchselect" name="direction">
                                            {% for direction in directions %}
                                                <option value="{{ direction.0 }}">{{ direction.1 }}</option>
                                            {% endfor %}
                                        </select>


                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn colored-button">Найти</button>
                                    </div>
                                </form>
                            </div>
                        </div>


                    </div>
                </div>
            </div>

            <div class="row">
                {% for course in courses %}
                    <div class="course-item col-sm-3 no-padding">
                        {% cloudinary course.image.url class="col-md-12 no-padding" %}
                        <hr class="line blue">


                        <div class="content" style="margin-left: 1em">
                            {{ course.creater }}
                            <p>
                                <strong>
                                    <a href="{% url 'courses:one' course.id %}">

                                        <span id="link-panel"></span>
                                    </a>
                                    {{ course.name }}


                                </strong>

                            </p>
                        </div>


                        {#                            <a class="btn colored-button text-center"#}
                        {#                               href="{% url 'courses:one' course.id %}"#}
                        {#                               role="button">Подробнее</a>#}
                    </div>

                {% endfor %}
            </div>


            <div class="text-center">
                <ul class="pagination">

                    {% if courses.has_previous %}
                        <li><a href="?page=

                                {{ courses.previous_page_number }}{% if search != None %}&search_text={{ search }}&direction={{ direction }}{% endif %}"><span>&laquo;</span></a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&laquo;</span></li>
                    {% endif %}

                    {% for i in courses.paginator.page_range %}
                        {% if courses.number == i %}
                            <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                        {% else %}
                            <li><a href="?page=
                                    {{ i }}{% if search != None %}&search_text={{ search }}&direction={{ direction }}{% endif %}">{{ i }}</a></li>
                        {% endif %}
                    {% endfor %}




                    {% if courses.has_next %}
                        <li><a href="?page=

                                {{ courses.next_page_number }}{% if search != None %}&search_text={{ search }}&direction={{ direction}}{% endif %}"><span>&raquo;</span></a>
                        </li>
                    {% else %}
                        <li class="disabled"><span>&raquo;</span></li>
                    {% endif %}

                </ul>
            </div>

        </div>
    </div>


{% endblock %}

courses/templates/courses/list_lections.html
{% extends "base.html"%}
{% load static %}
{% block main %}
    <div class="main-part">
        <div class="container" role="main">
            <div class="page-header">
                <h2>Список лекций курса <strong>'{{ course.name }}'</strong></h2>
            </div>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>№</th>
                    <th class="col-lg-9">Название лекции</th>
                    <th>Перейти</th>
                </tr>
                </thead>
                <tbody>
                {% for lection in lections %}
                <tr>
                    <td>{{ lection.order }}</td>
                    <td><h4>{{ lection.name }}</h4></td>
                    <td><a class="btn btn-lg btn-default" href="{% url 'courses:lection' lection.course.id lection.id %}" role="button">Перейти к лекции</a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

courses/templates/courses/list_tasks.html
{% extends "base.html" %}
{% load static %}
{% load courses_filters %}
{% load widget_tweaks %}
{% block main %}
    {% load cloudinary %}


    <div class="row">
        <a href="{% url 'courses:lection' course_id lection_id%}" role="button">Назад</a>
        <div class="col-lg-4 col-lg-offset-4">
            <div class="panel">
                <div class="panel-heading"><h3>Тест</h3>
                </div>
                <div class="panel-body">
                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% for k in answers.keys %}
                            {% if tasks|is_final:k %}
                                <div class="question">
                                <b>{{ k|get_final_question|safe }}</b>
                                </div>
                                {% if tasks|has_photo:k %}
                                {% cloudinary k|get_photo style="margin-top:2em" class="col-sm-11 img-responsive col-sm-offset-1" %}
                                    {% endif %}
                                {% if not tasks|answer_is_photo:k %}
                                <textarea class="form-control" name="{{ k|tostring }}" id="photo+{{ k|tostring }}"></textarea>
                                    {% else %}
                                    {{ f.file }}
                                {% endif %}
                            {% else %}
                            <div class="question">
                                <b>{{ k|get_question|safe }}</b>
                            </div>
                            {% for answer in answers|get_item:k %}
                                <div class="form-group">
                                <div class="col-lg-10">
                                    <label class="control-label" for="{{ answer }}">
                                        {% if not tasks|is_text:k %}{{ answer }}{% endif %}</label>
                                </div>
                                {% if tasks|is_checkbox:k %}
                                    <div class="col-lg-2">
                                    <input type="checkbox" name="{{ k |tostring }}" class="form-control"
                                           value="{{ answer }}" id="{{ answer }}">

                                {% elif tasks|is_radio:k %}
                                    <div class="col-lg-2">
                                    <input type="radio" class="form-control" name="{{ k|tostring }}"
                                           value="{{ answer }}" id="{{ answer }}">

                                {% else %}
                                    <div class="col-lg-12">
                                    <textarea minlength="1" class="form-control" name="{{ k|tostring }}" id="{{ answer }}"></textarea>

                                {% endif %}
                            </div>

                            </div>

                            {% endfor %}
                            {% endif %}
                            <hr>
                        {% endfor %}
                        <div class="spacing"></div>
                        <div class="form-group">
                            <input style="margin-top: 1em" type="submit" class="form-control btn blue-bg" name="" id="">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>



{% endblock %}

courses/templates/courses/main.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}"/>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
</head>
<body>

</body>
</html>

courses/templates/courses/show_certificates.html
{% extends "base.html" %}
{% load static %}
{% load cloudinary %}
{% block main %}
<div align="center"><h1>Сертификаты</h1></div>
    <hr style="border-top: 1px solid #737373">
{% if certificates %}
{% for cert in certificates %}
    <a href="{% url 'auth:certificates' %}?course_id={{ cert.course.id }}">{% cloudinary cert.image.url width="250px" height="250px" %}</a>
{% endfor %}
{% else %}

<div class="text-center">
<strong>У вас еще не было достижений</strong>
</div>
{% endif %}
{% endblock %}

courses/templates/courses/show_test.html
{% extends "base.html" %}
{% load static %}
{% block main %}
    <div class="main-part">
    <div class="container" role="main">
        <div class="page-header">
            <h1>Название курса</h1>
        </div>
        <div class="col-lg-12 lect-header">
            <h2>Лекция №1</h2>
        </div>
        <form role="form">
            <div class="form-group">
                <h3>Содержание вопроса № 1</h3>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" value="check1">
                        вариант 1
                    </label>
                </div>
                <div class="checkbox disabled">
                    <label>
                        <input type="checkbox" value="check2">
                        вариант 2
                    </label>
                </div>
            </div>
            <div class="form-group">
                <h3>Содержание вопроса № 1</h3>
                <div class="radio">
                    <label>
                        <input type="radio" name="optionsRadios" id="radio1" value="option1" checked>
                        Первый элемент списка из радиокнопок, её можно выбирать
                    </label>
                </div>
                <div class="radio">
                    <label>
                        <input type="radio" name="optionsRadios" id="radio22" value="option2">
                        Вторая опция списка, заблокированная
                    </label>
                </div>
                <div class="radio disabled">
                    <label>
                        <input type="radio" name="optionsRadios" id="radio3" value="option3">
                        Третья смешная опция
                    </label>
                </div>
            </div>
            <div class="form-group">
                <h3>Содержание вопроса № 3</h3>
                <input type="text" class="form-control" placeholder="Напишите свой ответ">
            </div>
            <div class="form-group">
                <h3>Содержание вопроса № 4</h3>
                <textarea class="form-control" rows="5" placeholder="Напишите свой ответ"></textarea>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-lg btn-default">Готово</button>
            </div>
        </form>
    </div>
</div>
{% endblock %}