auth/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import auth.views
import courses.views

urlpatterns = [
    url(r'login/', auth.views.logIn2, name="login"),
    url(r'logout/', auth.views.user_logout, name='logout'),
    url(r'register/', auth.views.register2, name="register"),
    url(r'user/(?P<userhash>-?\d+)', auth.views.confirmUser, name='confirm'),
    url(r'user/company$', auth.views.proposal_to_be_company, name='proposal_to_be_company'),
    url(r'user/profile$', auth.views.profile, name='profile'),
    url(r'user/profile/edit$', auth.views.profileEdit, name='edit'),
    url(r'user/proposal$', auth.views.proposal, name='proposal'),  # post_request
    url(r'user/proposal/(?P<hash>-?\d+)$', auth.views.confirmCompany, name='confirm_company'),
    url(r'user/proposal/(?P<hash>-?\d+)/delete$', auth.views.deleteCompany, name='delete_company'),
    url(r'user/unsubscribe$', auth.views.un_subscribe, name='un_teach'),
    url(r'certificates$',auth.views.show_certificates,name='certificates'),
]

courses/urls.py
from django.conf.urls import include, url
from courses import views

# Ставьте норм урлы, чо как в деревне

urlpatterns = [
    url(r'^courses/all$', views.list_courses, name='all'),
    url(r'^courses/search', views.course_search, name="search"),
    url(r'^courses/(?P<course_id>\d+)$', views.show_course, name='one'),
    url(r'^courses/(?P<course_id>\d+)/lections$', views.list_lections, name='lections'),
    url(r'^courses/(?P<course_id>\d+)/lections/(?P<lection_id>\d+)$', views.show_lection, name='lection'),
    url(r'^courses/(?P<course_id>\d+)/lections/(?P<lection_id>\d+)/tasks$', views.show_tasks, name='lection_task'),
    url(r'^courses/(?P<course_id>\d+)/reviews$', views.reviews, name='reviews'),
    url(r'^courses/(?P<course_id>\d+)/test$', views.show_test, name='test'),
    url(r'^courses/(?P<course_id>\d+)/support', views.support, name='support'),
    #url(r'^courses/(?P<course_id>\d+)/')
    url(r'^$', views.main, name='main')
]

project/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from auth import views
import auth.views
from courses import views
from project import settings

urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    url(r'^admin/', admin.site.urls, name='admin'),
    url(r'^auth/', include('auth.urls', namespace='auth')),
    url(r'^', include('courses.urls', namespace='courses'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
import datetime
import os

from django.contrib.auth.models import User
from django.db import models

from auth.models import Student

directions_of_training = (
    ('ALL', 'Все направления'),
    ('MNS', 'Математические и естественные науки'),
    ('ET', 'Инженерия, технологии и технические науки'),
    ('HMS', 'Здоровье и медицинские науки'),
    ('AS', 'Сельское хозяйство и сельскохозяйственные науки'),
    ('SS', 'Наука об обществе'),
    ('TS', 'Образование и наука о преподавании'),
    ('HS', 'Гуманитарные науки'),
    ('AC', 'Искусство и культура'),
)


# Create your models here.

def course_forlder(instance, filename):
    return 'courses_img/' + str(instance.name) + '/' + str(filename)


def task_folder(instance, filename):
    return 'tasks_img' + '/' + str(filename)


def user_task_folder(instance, filename):
    return 'users_img/' + str(instance.student.user.username) + "/" + str(filename)


def certificate_folder(instance, filename):
    return 'pdf/' + str(instance.student.user.username) + '/' + str(filename)


class Course(models.Model):
    class Meta:
        db_table = 'course'
        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'

    # Creater must been Company model now
    creater = models.ForeignKey('Company', on_delete=models.CASCADE, verbose_name='Компания курса')
    name = models.CharField(max_length=100, unique=True, null=False, blank=False, verbose_name='Название курса')
    about = models.TextField(max_length=3000, blank=True, null=True, verbose_name='О курсе')
    direction = models.CharField(max_length=3, choices=directions_of_training, verbose_name='Направление курса')
    date_begining = models.DateTimeField(default=datetime.datetime.today, null=True, verbose_name='Дата начала')
    date_ending = models.DateTimeField(null=True, verbose_name='Дата окончания')
    control_points = models.IntegerField(default=0, null=True,
                                         verbose_name='Минимальные очки за весь курс к допуску к теста')
    control_final_test_points = models.IntegerField(default=0, null=True,
                                                    verbose_name='Минимальные очки за итоговый тест')
    image = models.ImageField(upload_to=course_forlder, default='default_course.png', blank=True)
    next_course = models.OneToOneField('Course', null=True, blank=True, verbose_name='Следующий курс',
                                       related_name='course_next')

    def __str__(self):
        return '%s' % self.name


class Subscribe(models.Model):
    course = models.ForeignKey('Course', on_delete=models.CASCADE, related_name='sub_course', verbose_name='Курс')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='sub_student', verbose_name='Студент')
    points = models.IntegerField(blank=False, null=False, default=0, verbose_name='Очки студента')
    lection_status = models.ForeignKey('Lection', null=True, verbose_name='Текущая лекция')
    final_test_points = models.IntegerField(blank=False, null=False, default=-1,
                                            verbose_name='Очки студента за итоговый тест')

    class Meta:
        db_table = 'subscribes'
        unique_together = (('course', 'student'),)
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return self.student.user.first_name


# Component of course
class Lection(models.Model):
    course = models.ForeignKey('Course', on_delete=models.CASCADE, null=True, blank=False, related_name='lec_course',
                               default=None, verbose_name='Курс')
    name = models.CharField(max_length=100, blank=True, null=False, verbose_name='Название лекции')
    info = models.TextField(max_length=10000, blank=True, null=False, verbose_name='Лекционная информация')
    order = models.IntegerField(default=1, verbose_name='Порядковый номер')
    youtube_url = models.TextField(max_length=500, null=True, blank=True, verbose_name='YouTube-ссылка')
    is_final = models.BooleanField(default=False, verbose_name='Выберите v , если это лекция для финального теста.')

    class Meta:
        verbose_name = 'Лекцию'
        verbose_name_plural = 'Лекции'
        unique_together = (('course', 'order'),)

    def __str__(self):
        return '%s %s' % (self.name, '[Final Test]' if self.is_final else '')


# Who create course
class Company(models.Model):
    class Meta:
        verbose_name = 'Компания'
        verbose_name_plural = 'Компании'

    user = models.OneToOneField(Student, related_name='company_user', on_delete=models.CASCADE,
                                verbose_name='Пользователь')
    name = models.CharField(max_length=200, unique=True, null=False, blank=True, verbose_name='Название компании')
    about = models.TextField(max_length=45000, null=True, verbose_name='О компании')
    is_confirmed = models.BooleanField(default=False, verbose_name='Подтверждена')
    hash_code = models.TextField(default='')
    email_is_sended = models.BooleanField(default=False)

    def __str__(self):
        return '%s' % self.name

    def is_confirm(self):
        self.is_confirmed = True
        self.save()


class TeachersGroup(models.Model):
    class Meta:
        verbose_name = 'Группу'
        verbose_name_plural = 'Группа учителей'

    name = models.TextField(default='Учителя')
    company = models.OneToOneField('Company', related_name='company_teachers', on_delete=models.CASCADE,
                                   verbose_name='Компания', unique=True)
    teachers = models.ManyToManyField(Student, related_name='teacher_group', null=True)

    def __str__(self):
        return self.name


class Tasks(models.Model):
    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'

    TYPES = (
        ('checkbox', 'checkbox'),
        ('radio', 'radio'),
        ('text', 'text')
    )

    question = models.TextField(verbose_name='Вопрос')
    answers = models.ManyToManyField('Answers', related_name="all_answers", verbose_name='Все ответы')
    points = models.FloatField(verbose_name='Максимальное кол-во очков за задание')
    lection = models.ForeignKey('Lection', on_delete=models.CASCADE, related_name='lection', null=True,
                                verbose_name='Лекция')
    type = models.CharField(max_length=10, choices=TYPES)

    def __str__(self):
        return '%s' % self.question


class FinalTaskInFinalTest(models.Model):
    class Meta:
        verbose_name = "Задача для финального теста"
        verbose_name_plural = "Задачи для финального теста"

    question = models.TextField(verbose_name="Вопрос", default="")
    points = models.FloatField(verbose_name='Максимальное кол-во очков за задание', default=0)
    lection = models.ForeignKey('Lection', on_delete=models.CASCADE, related_name='course_final_task', null=True,
                                blank=True,
                                verbose_name='Выберите лекцию для финального теста*')
    photo = models.ImageField(upload_to=task_folder, null=True, blank=True,
                              verbose_name='Фото задания для финального теста*')
    answer_is_photo = models.BooleanField(default=False)

    def __str__(self):
        return self.question + ' [Final]'


class Answers(models.Model):
    creater = models.ForeignKey(Student, related_name='answer_student', on_delete=models.CASCADE, null=False,
                                verbose_name='Создатель ответа')
    answer_text = models.TextField(verbose_name='Текст ответа', null=False, blank=False)
    is_right = models.BooleanField(verbose_name="Правильный ?", null=False, blank=False)

    def __str__(self):
        return '%s %s' % (self.answer_text, '[Верный]' if self.is_right else '[Не верный]')

    class Meta:
        verbose_name = 'Ответ'
        db_table = 'answers'
        verbose_name_plural = 'Ответы'
        unique_together = (('creater', 'answer_text', 'is_right'),)


class StudentAnswers(models.Model):
    student = models.ForeignKey(Student, null=False, verbose_name='Студент')
    task = models.ForeignKey('Tasks', related_name="task", null=False, verbose_name='Задача')
    given_answers = models.ManyToManyField('Answers', related_name='given_answers', null=False,
                                           verbose_name='Ответ студента')
    text_answer = models.TextField(null=True)

    class Meta:
        db_table = 'student_answers'
        unique_together = (('student', 'task'),)
        verbose_name = 'Ответ студента'
        verbose_name_plural = 'Ответы студентов'

    def are_correct(self):
        if len(self.given_answers.all()) != len(self.task.answers.filter(is_right=True).all()):
            return False
        given_answers = self.given_answers.order_by('answer_text').only('answer_text')
        task_right_answers = self.given_answers.order_by('answer_text').only('answer_text')
        for i in range(0, len(given_answers)):
            if given_answers[i] != task_right_answers[i]:
                return False
        return True


class StudentFinalTestAnswers(models.Model):
    student = models.ForeignKey(Student, null=False, verbose_name="Клиент")
    task = models.ForeignKey(FinalTaskInFinalTest, related_name="finaltask_answer", verbose_name="Финальная задача")
    answer = models.TextField(null=True, blank=True, verbose_name="Ответ студента:")
    photo = models.ImageField(upload_to=user_task_folder, null=True, blank=True, verbose_name="Ответ студента:")
    is_solved = models.BooleanField(default=False, )

    def image_tag(self):
        return """<img src="http://res.cloudinary.com/educationsphere/image/upload/v1494417475/media/%s"/>""" % self.photo.name

    image_tag.short_description = 'Image'
    image_tag.allow_tags = True

    def __str__(self):
        return self.task.question + " : " + self.student.user.username

    class Meta:
        db_table = 'student_final_answers'
        unique_together = (('student', 'task'),)

templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Education Sphere</title>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}"/>
    <link href="{% static "css/comments.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/send_comment.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa" rel="stylesheet">
    <script src="https://use.fontawesome.com/fcddfd1d88.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'css/footerStyle.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

</head>
<body>
{% include "menu.html" %}
<div class="wrapper">
    {% block main %}{% endblock %}
</div>
{% include 'footer.html' %}


</body>
</html>

templates/menu.html
{% load static %}

<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href="{% url 'courses:main' %}"><p class="logo">EducationSphere</p></a>


        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'courses:all' %}">Список курсов</a></li>
                {% if request.user.is_authenticated %}
                    <li class="dropdown btn-toolbar">
                        <a id="drop1" href="#" class="dropdown-toggle" data-toggle="dropdown">
                            {% if request.user.is_superuser %}
                                Admin
                            {% else %}
                                {{ request.user.first_name }}
                            {% endif %}
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'auth:profile' %}">Профиль</a></li>
                            <li><a href="{% url 'auth:certificates' %}">Сертификаты</a></li>
                            <li><a href="{% url 'auth:logout' %}">Выйти</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="dropdown">
                        <a id="drop1" href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Гость
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'auth:login' %}">Войти</a></li>
                            <li><a href="{% url 'auth:register' %}">Зарегистрироваться</a></li>
                        </ul>
                    </li>
                {% endif %}

            </ul>
        </div><!--/.navbar-collapse -->
    </div>
</div>

templates/profile.html
{% extends "base.html" %}
{% load static %}
{% load courses_filters %}
{% load cloudinary %}


{% block main %}
{#        <script src="{% static 'js/matchHeight.js' %}"></script>#}
{#        <script>#}
{##}
{#            $(function () {#}
{#                $('.item').matchHeight();#}
{#            });#}
{#        </script>#}


    <div class="main-part">
        <div class="container" role="main">
            <div class="page-header"><h2><strong>Мой профиль</strong></h2></div>


            <div class="col-md-12 profile">
                <div class="row">
                    <div class="col-md-2">
                        {% cloudinary student.photo.url width=184 height=184 crop="thumb" radius="max" %}
                    </div>
                    <div class="col-md-offset-1 col-md-5">

                        <h4><strong>Имя : </strong>{{ student.user.first_name }} {{ student.user.last_name }}</h4>
                        <h4><strong>Почта: </strong>{{ student.user.username }}</h4>
                        <h4><strong>Дата рождения: </strong>{{ student.birthday }}</h4>
                        <h4><strong>Город: </strong>{{ student.city }}</h4>
                        <h4><strong>Место обучения: </strong>{{ student.university }}</h4>
                        <h4><strong>Текущий статус: </strong> Студент </h4>
                        {% if company %}
                            <h4><strong>Компания: </strong> {{ company.name }}</h4>
                        {% endif %}
                        {% if teacher_group %}
                            <h4><strong>Курирует компанию(-и):</strong>{% for t in teacher_group %}
                                <li style="margin-left: 50px; margin-top: 10px;">{{ t.company.name }}</li>
                            {% endfor %}</h4>
                        {% endif %}
                    </div>


                    <div class="col-md-4">
                        <ul class="nav side-menu">
                            <li><a href="{% url 'auth:edit' %}">
                                Редактировать профиль
                                <span class="glyphicon glyphicon-edit pull-right"></span></a>
                            </li>
                            <li class="divider"></li>


                            {% if request.user.is_superuser %}
                                <li>
                                    <a href="/admin/">Режим администрирования</a>
                                </li>

                            {% else %}
                                {% if teacher_group %}
                                    {% for t in teacher_group %}
                                        <li>
                                            <a href="/admin/" style="margin-top: 10px;">Режим
                                                преподавания {{ t.company.name }} компании</a>
                                        </li>

                                        <li>
                                            <form action="{% url 'auth:un_teach' %}" method="post">
                                                {% csrf_token %}
                                                <input type="submit" class="cust-inp"
                                                       value="Отписаться от курирования {{ t.company.name }} компании."/>
                                                <input type="hidden" name="teacher_group_name"
                                                       value="{{ t.company.name }}"/>
                                            </form>
                                        </li>
                                    {% endfor %}

                                {% elif not company %}

                                    <li><a href="{% url 'auth:proposal_to_be_company' %}">
                                        Создать курс <span class="glyphicon glyphicon-stats pull-right"></span></a></li>
                                {% else %}
                                    {% if company.is_confirmed %}
                                        <li><a href="/admin/">
                                            Управление курсами <span
                                                class="glyphicon glyphicon-stats pull-right"></span></a>
                                        </li>
                                        <li>
                                            <form action="{% url 'auth:delete_company'  company.hash_code %}"
                                                  method="post">
                                                {% csrf_token %}
                                                <input type="submit" style="background-color: #E53935" class="cust-inp"
                                                       value="Удалить компанию">

                                                <input type="hidden" name="company_name" value="{{ company.name }}"/>
                                            </form>
                                        </li>
                                        <li class="divider"></li>

                                    {% else %}
                                        <li>
                                            <a href="auth/user/proposal/{{ company.hash_code }}?parameter=company>">Отправить
                                                повторную заявку<span
                                                        class="glyphicon glyphicon-repeat pull-right"></span></a></li>
                                        <li>
                                            <form action="{% url 'auth:delete_company' company.hash_code %}"
                                                  method="post">
                                                {% csrf_token %}
                                                <input type="submit" style="background-color: #E53935" class="cust-inp"
                                                       value="Удалить заявку."/>
                                                <input type="hidden" name="company_name" value="{{ company.name }}"/>
                                            </form>
                                        </li>

                                    {% endif %}
                                {% endif %}


                            {% endif %}

                            <li class="divider"></li>
                            <li><a href="{% url 'auth:logout' %}">Выйти<span
                                    class="glyphicon glyphicon-log-out pull-right"></span></a></li>
                        </ul>
                    </div>
                </div>
            </div>


            <div class="row subscribes">
                <div class="page-header text-center"><h2><strong>Мои подписки</strong></h2></div>

                {% if subscribe %}
                    <div class="col-md-12 owl-carousel owl-theme">
                        {% for sub in subscribe %}
                            <div class="course-item item no-padding text-center">
                                {% cloudinary sub.course.image.url style="height: 14em;" class="col-md-12 no-padding" %}

                                <hr class="line blue">

                                <div class="text-center">
                                    <h4><strong>{{ sub.course.name }}</strong></h4>
                                    <p style="margin-top: -6px">Прогресс: {% progress sub %}</p>
                                </div>

                                <div class="abc" style="margin: 1em; position: absolute;
                                     bottom: 0; left: 0; right: 0;">
                                    <a class="btn colored-button text-center" role="button" style="margin-bottom: 1em;"
                                       href="{% url 'courses:one' sub.course.id %}">
                                        Перейти
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% else %}
                    <div class="text-center" style="margin-bottom: 1em">
                        <h3>У вас еще нет курсов</h3>
                    </div>
                {% endif %}
            </div>


            <div class="row my-courses" style="margin-top:2em;">
                {% if company.is_confirmed %}
                    <div class="page-header text-center"><h2><strong>{{ company.name }}</strong></h2></div>
                    <div class="col-md-12 owl-carousel owl-theme ">
                        {% if company.course_set.all %}
                            {% for course in company.course_set.all %}
                                <div class="course-item item no-padding text-center">
                                    {% cloudinary course.image.url style="height: 14em;" class="col-md-12 no-padding" %}

                                    <hr class="line purple">
                                    <span class="course-name">
                                        <h4><strong>{{ course.name }}</strong></h4>

                                    </span>

                                    <div>
                                        {{ course.creater }}
                                    </div>

                                    <div class="abc" style="margin: 1em; position: absolute;
                                     bottom: 0; left: 0; right: 0">
                                        <a class="btn colored-button text-center"
                                           href="{% url 'courses:one' course.id %}"
                                           role="button" style="margin-bottom: 1em;">Подробнее</a></div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="text-center" style=" margin-bottom: 2em">

                                <a class="btn btn-sm colored-button" href="/admin/" role="button">Перейти в
                                    режим
                                    управления курса.</a>
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
            </div>
        </div>
    </div>



    <script src="{% static 'js/owl.carousel.js' %}"></script>
    <script>
        $('.owl-carousel').owlCarousel({
            nav: true,
            loop: false,
            margin: 15,
            navText: [
                "Вперед",
                "Назад"
            ],
            responsive: {
                0: {
                    items: 1
                }
                ,
                600: {
                    items: 3
                }
                ,
                1000: {
                    items: 3
                }
            }
        })
    </script>


{% endblock %}

templates/proposal_to_be_company.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}


{% block main %}
    <div class="middlePage">
        <div class="page-header my-page-header">
            <h2 class="panel-logo">EducationSphere
            </h2>
            <p>Создайте свой соственный курс</p>

        </div>

        <div class="panel panel-info no-border-panel">
            <div class="panel-heading" id="my_panel_head">
                <h3 class="panel-title">Расскажите о своей компании.</h3>
            </div>


            <div class="panel-body">
                <div class="errors row text-center" id="errors" style="color: red">
                    {% if messages %}
                        <div class="col-md-6 col-sm-offset-6">
                            <ul class="messages">
                                {% for message in messages %}
                                    <li{% if message.tags %}
                                        class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}
                </div>
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">
                        <form method="post" class="registration_form" id="proposal-form"
                              action="{% url 'auth:proposal_to_be_company' %}">
                            {% csrf_token %}
                            <div class="form-group spacing ">
                                <label class="col-sm-3 control-label" for="name">Название:</label>
                                <div class="col-sm-9">{% render_field form.name class="form-control input-sm" id='company_name' type="text" %}
                                </div>
                            </div>
                            <div class="spacing"></div>

                            <div class="form-group spacing">
                                <label for="first_name" class="control-label col-sm-3">О компании:</label>
                                <div class="col-sm-9">
                                    {% render_field form.about class="form-control input-sm" id="about" type="textarea" %}
                                </div>
                            </div>

                            <div class="spacing"></div>
                            <div class="form-group spacing">
                                <div class="text-center">
                                    <input type="submit" id="submit" value="Отправить заявку"
                                           style="margin-top: 1em;" class="btn colored-button">

                                    <div id="myModal" class="modal fade">
                                        <div class="modal-dialog">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <button class="close" type="button">
                                                        <a href="{% url 'courses:main' %}">×</a>
                                                    </button>
                                                    <h4 class="modal-title">Уведомление</h4>
                                                </div>
                                                <div class="modal-body"><p>Ваша заявка успешно отправлена.</p>
                                                    После того, как мы подтвердим ее, Вы сможете создать свой курс.
                                                    Для этого Вам необходимо перейти на страницу профиля и перейти в
                                                    раздел управления курсами.
                                                </div>
                                                <div class="modal-footer">
                                                    <button class="btn btn-default" type="button">
                                                        <a href="{% url 'auth:profile' %}">Профиль</a>
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>


                                </div>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'js/modalWindow.js' %}"></script>
{% endblock main %}